title:        featureenvy
tagline:      'Because having feature envy is stupid.'
description:  'The blog of a thinkerer. <br>By <a href="https://twitter.com/featureenvy">@featureenvy</a>'
url:          http://feautreenvy.com
version:      1.1.1
author:       
  name:       'Andreas Arnold'
  email:      'andreas@featureenvy.com'
markdown:     kramdown
permalink:    '/blog/:title'
highlighter:  pygments
paginate:     5

host: 0.0.0.0

gems:
    - jekyll-paginate
